export enum ConfigKey {
  APP_NAME = 'APP_NAME',
  APP_DESCRIPTION = 'APP_DESCRIPTION',
  APP_PORT = 'APP_PORT',
  MONGO_USERNAME = 'MONGO_USERNAME',
  MONGO_PASSWORD = 'MONGO_PASSWORD',
  MONGO_HOSTNAME = 'MONGO_HOSTNAME',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_DB = 'MONGO_DB',
  WEB_BASE_PATH = 'WEB_BASE_PATH',
  JWT_SECRET = 'JWT_SECRET',
  ADMINS = 'ADMINS',
  NAYTRADING_URL = 'NAYTRADING_URL'
}
