/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id: string;
    createdAt: string;
    updatedAt: string;
    username: string;
    isAdmin: boolean;
    isSuspended: boolean;
    activationRequestToken: string;
    activationRequestDate: string;
    activationRequestTries: number;
    activationDate: string;
    changeEmail: string;
    changeEmailRequestToken: string;
    changeEmailRequestDate: string;
    changeEmailRequestTries: number;
    changeEmailDate: string;
    resetPasswordDate: string;
    name: string;
}

